version: 2.1
references:
  workspace_root: &workspace_root
    /tmp/workspace
  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root
jobs:
    build:
        docker:
            - image: circleci/openjdk:11-jdk-node
        working_directory: ~/repo
        environment:
            MAVEN_OPTS: -Xmx3200m
            
        steps:
            - *attach_workspace
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "pom.xml" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            
            - run: mvn dependency:go-offline
            - save_cache:
                paths:
                    - ~/.m2
                key: v1-dependencies-{{ checksum "pom.xml" }}
                
            # Execute Threat Scan
            - run:
                name: Install Threatrix ThreatAgent
                command: |
                    curl -L https://github.com/threatrix/threat-matrix/releases/download/v1.0.0-RC2/threat-agent-1.0.0.jar > threatagent.jar
                
            - run:
                name: ThreatAgent Scan
                command: java -jar threatagent.jar --progress --env=stage ./
                    
workflows:
    version: 2
    build_and_test:
        jobs:
            - build
